### ISSUE TITLE
Iterates over existing files 🤔

### ISSUE THREAD

**Issue by eduarguz** [bakle/laravel-translator#3]
Looks like it is iterating over existing files

It processes the `home.php` file here...
![image](https://user-images.githubusercontent.com/14934055/79997187-e458ec00-847e-11ea-8f21-340ec71cee74.png)
A few seconds later, in the same process, it tries to process the same `home.php` file
![image](https://user-images.githubusercontent.com/14934055/79997288-07839b80-847f-11ea-86ae-cd2a49214fb5.png)

**Comment by egarcam** [comment]
This was solved in commit 64cf4fdcc0aa3e084e57ec305c0b6943797133fb, can be closed.
